### ISSUE TITLE
Not working on iOS simulator?

### ISSUE THREAD

**Issue by tuantvu** [decodedhealth/flutter_zoom_plugin#3]
Got project to build and launched the example, but after entering a valid meeting id with no password, just get a blank "Loading meeting" Screen. Getting this in Android Studio debug:

flutter: Created the view
flutter: initialised
flutter: [1, 0]
[VERBOSE-2:platform_view_layer.cc(22)] Trying to embed a platform view but the PrerollContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(31)] Trying to embed a platform view but the PaintContext does not support embedding 
(repeated a dozen times)

**Comment by kevinbayes** [comment]
Hi,

Just checkin did you add your zoom app key, secret and domain (if needed) to:
```https://github.com/decodedhealth/flutter_zoom_plugin/blob/master/example/lib/meeting_screen.dart```?

The flutter: [1, 0] means that the zoom sdk did not initialise properly, perhaps due to the app key and secret.

Past that the error in the log indicates that the preview needs to be enabled in the Info.plist which I will push shortly.

**Comment by kevinbayes** [comment]
@tuantvu did that work for you?

**Comment by kevinbayes** [comment]
Close due to inactivity

**Comment by tuantvu** [comment]
Sorry about that, I was out of town. I will test and try again, but that was probably the problem. Thanks
